# generated by zon2nix (https://github.com/nix-community/zon2nix)

{ linkFarm, fetchzip }:

linkFarm "zig-packages" [
  {
    name = "12205e2e7108385a1ec280b6365166e902a690d6a0e8fcc015fdea62d63cf79be8ec";
    path = fetchzip {
      url = "https://codeberg.org/dude_the_builder/zg/archive/master.tar.gz";
      hash = "sha256-1dtXCXCsnQLWzfXaPjMUV+9+ZAwCwr2uaLoGaJobr/E=";
    };
  }
]
